	td_infos[playerid][0] = CreatePlayerTextDraw(playerid, 502.723266, 156.333312, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][0], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_infos[playerid][0], 119.941421, 106.166648);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][0], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][0], 0xA52A2AFF);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][0], 0);
	PlayerTextDrawFont(playerid, td_infos[playerid][0], 4);

	td_infos[playerid][1] = CreatePlayerTextDraw(playerid, 495.758666, 153.833312, "ld_beat:chit");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][1], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_infos[playerid][1], 12.181559, 14.583341);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][1], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][1], 0xA52A2AFF);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][1], 0);
	PlayerTextDrawFont(playerid, td_infos[playerid][1], 4);

	td_infos[playerid][2] = CreatePlayerTextDraw(playerid, 616.231689, 153.666656, "ld_beat:chit");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][2], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_infos[playerid][2], 12.181559, 14.583341);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][2], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][2], 0xA52A2AFF);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][2], 0);
	PlayerTextDrawFont(playerid, td_infos[playerid][2], 4);

	td_infos[playerid][3] = CreatePlayerTextDraw(playerid, 495.821563, 249.916549, "ld_beat:chit");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][3], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_infos[playerid][3], 12.181559, 14.583341);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][3], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][3], 0xA52A2AFF);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][3], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][3], 0);
	PlayerTextDrawFont(playerid, td_infos[playerid][3], 4);

	td_infos[playerid][4] = CreatePlayerTextDraw(playerid, 615.826232, 250.333328, "ld_beat:chit");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][4], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_infos[playerid][4], 12.181559, 14.000007);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][4], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][4], 0xA52A2AFF);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][4], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][4], 0);
	PlayerTextDrawFont(playerid, td_infos[playerid][4], 4);

	td_infos[playerid][5] = CreatePlayerTextDraw(playerid, 498.038055, 161.000000, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][5], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_infos[playerid][5], 128.374847, 96.250000);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][5], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][5], 0x191919FF);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][5], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][5], 0);
	PlayerTextDrawFont(playerid, td_infos[playerid][5], 4);

	td_infos[playerid][6] = CreatePlayerTextDraw(playerid, 562.694213, 163.916656, "~g~HOUSE ID");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][6], 0.250878, 1.150833);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][6], 2);
	PlayerTextDrawColor(playerid, td_infos[playerid][6], -1);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][6], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][6], 0);
	PlayerTextDrawBackgroundColor(playerid, td_infos[playerid][6], 51);
	PlayerTextDrawFont(playerid, td_infos[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, td_infos[playerid][6], 1);

	td_infos[playerid][7] = CreatePlayerTextDraw(playerid, 504.660186, 180.666671, "OWNER: Yevhen_Kosovskyi");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][7], 0.250878, 1.150833);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][7], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][7], -1);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][7], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][7], 0);
	PlayerTextDrawBackgroundColor(playerid, td_infos[playerid][7], 51);
	PlayerTextDrawFont(playerid, td_infos[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, td_infos[playerid][7], 1);

	td_infos[playerid][8] = CreatePlayerTextDraw(playerid, 504.723114, 192.166656, "COST: $0");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][8], 0.250878, 1.150833);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][8], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][8], -1);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][8], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][8], 0);
	PlayerTextDrawBackgroundColor(playerid, td_infos[playerid][8], 51);
	PlayerTextDrawFont(playerid, td_infos[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, td_infos[playerid][8], 1);

	td_infos[playerid][9] = CreatePlayerTextDraw(playerid, 504.786071, 203.083312, "CLASS: 1");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][9], 0.250878, 1.150833);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][9], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][9], -1);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][9], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][9], 0);
	PlayerTextDrawBackgroundColor(playerid, td_infos[playerid][9], 51);
	PlayerTextDrawFont(playerid, td_infos[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, td_infos[playerid][9], 1);

	td_infos[playerid][10] = CreatePlayerTextDraw(playerid, 504.848968, 213.999969, "ROOMS: 2");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][10], 0.250878, 1.150833);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][10], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][10], -1);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][10], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][10], 0);
	PlayerTextDrawBackgroundColor(playerid, td_infos[playerid][10], 51);
	PlayerTextDrawFont(playerid, td_infos[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, td_infos[playerid][10], 1);

	td_infos[playerid][11] = CreatePlayerTextDraw(playerid, 504.443420, 224.916610, "STATUS: Open");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][11], 0.250878, 1.150833);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][11], 1);
	PlayerTextDrawColor(playerid, td_infos[playerid][11], -1);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][11], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][11], 0);
	PlayerTextDrawBackgroundColor(playerid, td_infos[playerid][11], 51);
	PlayerTextDrawFont(playerid, td_infos[playerid][11], 1);
	PlayerTextDrawSetProportional(playerid, td_infos[playerid][11], 1);

	td_infos[playerid][12] = CreatePlayerTextDraw(playerid, 563.071899, 245.166610, "~y~PRESS ~g~N ~y~TO BUY");
	PlayerTextDrawLetterSize(playerid, td_infos[playerid][12], 0.202620, 0.940833);
	PlayerTextDrawAlignment(playerid, td_infos[playerid][12], 2);
	PlayerTextDrawColor(playerid, td_infos[playerid][12], -1);
	PlayerTextDrawSetShadow(playerid, td_infos[playerid][12], 0);
	PlayerTextDrawSetOutline(playerid, td_infos[playerid][12], 0);
	PlayerTextDrawBackgroundColor(playerid, td_infos[playerid][12], 51);
	PlayerTextDrawFont(playerid, td_infos[playerid][12], 1);
	PlayerTextDrawSetProportional(playerid, td_infos[playerid][12], 1);