            InfColorChange[playerid][0] = CreatePlayerTextDraw(playerid, 207.9998, 222.1999, "LD_SPAC:white"); // œŒﬂ¬À≈Õ»≈ »Õ‘ Œ «¿“Œ◊ ≈ (4)
            PlayerTextDrawLetterSize(playerid, InfColorChange[playerid][0], 0.4799, 1.1200);
            PlayerTextDrawTextSize(playerid, InfColorChange[playerid][0], 50.0000, 12.0000);
            PlayerTextDrawAlignment(playerid, InfColorChange[playerid][0], 1);
            PlayerTextDrawColor(playerid, InfColorChange[playerid][0], 92);
            PlayerTextDrawBackgroundColor(playerid, InfColorChange[playerid][0], 255);
            PlayerTextDrawFont(playerid, InfColorChange[playerid][0], 4);
            PlayerTextDrawSetProportional(playerid, InfColorChange[playerid][0], 0);
            PlayerTextDrawSetShadow(playerid, InfColorChange[playerid][0], 0);

            InfColorChange[playerid][1] = CreatePlayerTextDraw(playerid, 207.9998, 235.4739, "LD_SPAC:white"); // œŒﬂ¬À≈Õ»≈ »Õ‘ Œ «¿“Œ◊ ≈ (4)
            PlayerTextDrawLetterSize(playerid, InfColorChange[playerid][1], 0.4799, 1.1200);
            PlayerTextDrawTextSize(playerid, InfColorChange[playerid][1], 50.0000, 12.0000);
            PlayerTextDrawAlignment(playerid, InfColorChange[playerid][1], 1);
            PlayerTextDrawColor(playerid, InfColorChange[playerid][1], 92);
            PlayerTextDrawBackgroundColor(playerid, InfColorChange[playerid][1], 255);
            PlayerTextDrawFont(playerid, InfColorChange[playerid][1], 4);
            PlayerTextDrawSetProportional(playerid, InfColorChange[playerid][1], 0);
            PlayerTextDrawSetShadow(playerid, InfColorChange[playerid][1], 0);            
            
            InfColorChange[playerid][2] = CreatePlayerTextDraw(playerid, 233.9998, 237.2888, "$50000"); // œŒﬂ¬À≈Õ»≈ »Õ‘ Œ «¿“Œ◊ ≈ (3)
            PlayerTextDrawLetterSize(playerid,  InfColorChange[playerid][2], 0.1490, 0.8751);
            PlayerTextDrawTextSize(playerid,  InfColorChange[playerid][2], 54.0000, 1.1282);
            PlayerTextDrawAlignment(playerid,  InfColorChange[playerid][2], 2);
            PlayerTextDrawColor(playerid,  InfColorChange[playerid][2], -1);
            PlayerTextDrawUseBox(playerid,  InfColorChange[playerid][2], 1);
            PlayerTextDrawBoxColor(playerid,  InfColorChange[playerid][2], 16777216);
            PlayerTextDrawBackgroundColor(playerid,  InfColorChange[playerid][2], 255);
			PlayerTextDrawFont(playerid,  InfColorChange[playerid][2], 2);
            PlayerTextDrawSetProportional(playerid,  InfColorChange[playerid][2], 1);
            PlayerTextDrawSetShadow(playerid,  InfColorChange[playerid][2], 0);

            InfColorChange[playerid][3] = CreatePlayerTextDraw(playerid, 208.0001, 222.6145, "LD_SPAC:white");
            PlayerTextDrawLetterSize(playerid, InfColorChange[playerid][3], 0.4799, 1.1200);
            PlayerTextDrawTextSize(playerid, InfColorChange[playerid][3], 2.0000, 11.0000);
            PlayerTextDrawAlignment(playerid, InfColorChange[playerid][3], 1);
            PlayerTextDrawColor(playerid, InfColorChange[playerid][3], PI[playerid][pColorInv]);
            PlayerTextDrawBackgroundColor(playerid, InfColorChange[playerid][3], 255);
            PlayerTextDrawFont(playerid, InfColorChange[playerid][3], 4);
            PlayerTextDrawSetProportional(playerid, InfColorChange[playerid][3], 0);
            PlayerTextDrawSetShadow(playerid, InfColorChange[playerid][3], 0);

            InfColorChange[playerid][4] = CreatePlayerTextDraw(playerid, 208.0000, 235.8885, "LD_SPAC:white"); // œŒﬂ¬À≈Õ»≈ »Õ‘ Œ «¿“Œ◊ ≈ (2)
            PlayerTextDrawLetterSize(playerid,  InfColorChange[playerid][4], 0.4799, 1.1200);
            PlayerTextDrawTextSize(playerid,  InfColorChange[playerid][4], 2.0000, 11.0000);
            PlayerTextDrawAlignment(playerid,  InfColorChange[playerid][4], 1);
            PlayerTextDrawColor(playerid,  InfColorChange[playerid][4], PI[playerid][pColorInv]);
            PlayerTextDrawBackgroundColor(playerid,  InfColorChange[playerid][4], 255);
            PlayerTextDrawFont(playerid,  InfColorChange[playerid][4], 4);
            PlayerTextDrawSetProportional(playerid,  InfColorChange[playerid][4], 0);
            PlayerTextDrawSetShadow(playerid,  InfColorChange[playerid][4], 0);

            InfColorChange[playerid][5] = CreatePlayerTextDraw(playerid, 233.9998, 223.6000, !PI[playerid][pLanguage] ? "CHANCE:5.0" : FixText("ÿ¿Õ—:5.0")); // œŒﬂ¬À≈Õ»≈ »Õ‘ Œ «¿“Œ◊ ≈ (5)
            PlayerTextDrawLetterSize(playerid, InfColorChange[playerid][5], 0.1490, 0.8751);
            PlayerTextDrawTextSize(playerid, InfColorChange[playerid][5], 54.0000, 1.1282);
            PlayerTextDrawAlignment(playerid, InfColorChange[playerid][5], 2);
            PlayerTextDrawColor(playerid, InfColorChange[playerid][5], -1);
            PlayerTextDrawUseBox(playerid, InfColorChange[playerid][5], 1);
            PlayerTextDrawBoxColor(playerid, InfColorChange[playerid][5], 16777216);
            PlayerTextDrawBackgroundColor(playerid, InfColorChange[playerid][5], 255);
            PlayerTextDrawFont(playerid, InfColorChange[playerid][5], 2);
            PlayerTextDrawSetProportional(playerid, InfColorChange[playerid][5], 1);
            PlayerTextDrawSetShadow(playerid, InfColorChange[playerid][5], 0);

            